language: python
sudo: false

python:
  - "3.6"

services:
  - docker

script:
  - echo "PR = $TRAVIS_PULL_REQUEST"
  - echo "branch = $TRAVIS_BRANCH"
  - ./checkendline
  - docker build -t buildozer3 .

after_success:
  - ./dockerhubpush
