language: python
sudo: false

python:
  - "3.6"

services:
  - docker

script:
  - echo "PR = $TRAVIS_PULL_REQUEST"
  - echo "branch = $TRAVIS_BRANCH"
  - ./checkendline
  - |
    status=$(curl -s --head -w %{http_code} https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip -o /dev/null)
    if [ "$status" != "200" ]; then
      exit 1
    fi
  - docker build -t buildozer3 .

after_success:
  - docker images
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      curl -H "Content-Type: application/json" --data '{"source_type": "Branch", "source_name": "master"}' -X POST https://cloud.docker.com/api/build/v1/source/"$DOCKER_ID"/trigger/"$DOKCER_KEY"/call/
    fi
