language: python
sudo: false

python:
  - "3.6"

services:
  - docker

script:
  - echo "PR = $TRAVIS_PULL_REQUEST"
  - echo "branch = $TRAVIS_BRANCH"
  - ./checkendline
  - docker build -t buildozer3 .

after_success:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      curl --data build=true -X POST https://cloud.docker.com/api/build/v1/source/"$DOCKER_ID"/trigger/"$DOKCER_KEY"/call/
    fi
